Algoritmo "Vetor Ex. 1"

// Descrição   : Estudo de Vetores
// Autor(a)    : BPresstes
// Data atual  : 29/06/2026

Var

   letra: vetor [1..4] de caractere
   i: inteiro

Inicio

      Para i de 1 ate 4 Faca
      
           Escreval( "Digite uma Letra: " )
           Leia( letra [ i ] )
           escreval
      
      FimPara
      
      escreval
      Escreval("Letra Posição 1: ", letra [ 1 ] )
      Escreval("Letra Posição 2: ", letra [ 2 ] )
      Escreval("Letra Posição 3: ", letra [ 3 ] )
      Escreval("Letra Posição 4: ", letra [ 4 ] )
      escreval

Fimalgoritmo