Algoritmo "Repita Ate Letra for Igual a A"

// Descrição   : Estudo da Função Repita Até com a limitação por caractere específico
// Autor(a)    : BPresstes
// Data atual  : 29/06/2026

Var

   letra: caractere

Inicio

      // Repita

      // <Instruções a serem executadas repetidamente até a expressão booleana retornar VERDADEIRO>

      // Ate <expressão booleana>
      //Ex.:
      
      Repita
      
            Escreval("Digite uma letra: ")
            Leia(letra)
            escreval
            
      Ate ( letra = "a" ) ou ( letra = "A" )
      
      escreval
      Escreval("Muito Bem!!! Você digitou a letra A. ")
      escreval
      
Fimalgoritmo